project_id = "task-app-project"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]

[database]
port = 54322

[database_seed]
enabled = true
sql_paths = ['./seed.sql']

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[file_storage]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"
image_transformation = true

[authentication]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
allow_user_signup = true

[authentication.email]
allow_user_signup = true
require_double_confirmation_for_changes = true
enable_confirmations = false